version: "3.8"
#List of networks for Docker-Compose
networks:
  maxminded-ntw-compose:
    external:
      name: maxminded-ntw-compose

#service template
x-mongodb:
  &mongodb
  restart: unless-stopped
  volumes:
    - ./entry.js:/docker-entrypoint-initdb.d/entry.js
  networks:
    - maxminded-ntw-compose
  env_file:
    - .env

#this config is automatically applied when using docker compose up
services:
  mongo1:
    <<: *mongodb
    container_name: mongo1
#    command:
#      - mongod
  mongo2:
    <<: *mongodb
    container_name: mongo2
  mongo3:
    <<: *mongodb
    container_name: mongo3

