version: "3.7"

volumes:
  mongo-keyfile:
    external: true
  mongo-data-1:
  mongo-data-2:
  mongo-data-3:
  mongo-config-1:
  mongo-config-2:
  mongo-config-3:

#service template
x-mongodb:
  &mongodb
  environment:
    MONGO_INITDB_DATABASE: admin
    MONGO_DATABASE: maxminded
  image: mongo:5.0.9
  labels:
    docker.service: mongodb
  command: --keyFile /data/keyfile/keyfile --replSet 'rs1'
  deploy:
    replicas: 1

#This is the base service for production and development
#list of services
services:
  mongo1:
    <<: *mongodb
    labels:
      docker.service: manager
    volumes:
      - mongo-data-1:/data/db
      - mongo-config-1:/data/configdb
      - mongo-keyfile:/data/keyfile
  mongo2:
    <<: *mongodb
    volumes:
      - mongo-data-2:/data/db
      - mongo-config-2:/data/configdb
      - mongo-keyfile:/data/keyfile
  mongo3:
    <<: *mongodb
    volumes:
      - mongo-data-3:/data/db
      - mongo-config-3:/data/configdb
      - mongo-keyfile:/data/keyfile